[package]
name = "stream-program"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
queues = "1.1.0"
tokio = {version = "1.40.0", features = ["full"]}
tts = "0.26.3"
twitch-irc = "5.0.1"
youtube_chat = "0.2.1"
