[package]
name = "stream-program"
version = "0.1.0"
edition = "2021"

[dependencies]
brainrot = "0.1.0"
chrono = "0.4.38"
futures-util = "0.3.30"
iced = "0.13.1"
queues = "1.1.0"
tokio = {version = "1.40.0", features = ["full"]}
tts = "0.26.3"
